services:

  backend:
    image: backend:alpha
    ports:
      - "3030:3030"
    environment:
      TOKEN_SECRET: tokensecret
    links:
      - "postgress:database"
  frontend:
    image: frontend:alpha
    environment:
      NEXTAUTH_SECRET: tokensecret
    ports:
      - "3000:3000"
    links:
      - "backend:backend"

  relayer:
    image: relayer:alpha
    ports:
      - "80:80"
    links:
      - "frontend:frontend"
      - "backend:backend"
  postgress:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: Custom
    ports:
      - "5430:5432"
    volumes:
      - ./data:/Users/mac/Documents/work2/dockertask/postgressdemo


#/var/www/ampouletude.com/html/source/postgressdemo